# Generated by Django 5.1 on 2024-08-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chat_room',
        ),
    ]
